# Generated by Django 6.0.1 on 2026-01-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='related_topics',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='summary',
        ),
    ]
